# Generated by Django 5.1.6 on 2025-03-13 01:04

import publicacion.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=publicacion.storages.ImageStorage(), upload_to='posts/'),
        ),
    ]
