# Generated by Django 5.1.6 on 2025-03-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_publicacion_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='image',
            new_name='imagen',
        ),
    ]
