# Generated by Django 5.1.6 on 2025-04-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_publicacion_likes_publicacion_reportes'),
        ('registro', '0003_alter_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='hashtags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='reportes',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='registro.profile'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicacion.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.profile')),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_publicaciones', to='registro.profile'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='reportes',
            field=models.ManyToManyField(blank=True, related_name='reportes_publicaciones', to='registro.profile'),
        ),
    ]
