# Generated by Django 5.1.6 on 2025-04-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_alter_publicacion_hashtags_remove_publicacion_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='comentarios/'),
        ),
    ]
