# Generated by Django 4.2.20 on 2025-06-08 23:35

from django.db import migrations, models
import publicacion.storages


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0007_alter_comentario_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='archivo_media',
            field=models.FileField(blank=True, null=True, storage=publicacion.storages.ImageStorage(), upload_to='posts/'),
        ),
    ]
