# Generated by Django 4.2.20 on 2025-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('like', 'Like'), ('comentario', 'Comentario'), ('reporte', 'Reporte'), ('eliminado', 'Eliminado')], max_length=20),
        ),
    ]
