# Generated by Django 5.1.6 on 2025-03-30 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('seleccion', 'Selecciona el gesto correcto para {palabra}'), ('seleccion2', 'Selecciona el gesto correcto a la palanra resaltada'), ('emparejar', 'Empareja las palabras con su respectivo texto'), ('completar', 'Selecciona el gesto que completa la frase'), ('escribir', 'Escribe la palabra que corresponde al gesto'), ('gesto', 'Realiza el siguiente gesto para la palabra {palabra}')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='ejercicio.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='ejercicio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
                ('nueva', models.BooleanField(default=True)),
                ('ejemplos', models.TextField(default='')),
                ('gesto', models.ImageField(default='gestos/default.jpg', upload_to='gestos/')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras', to='ejercicio.leccion')),
            ],
        ),
    ]
