# Generated by Django 5.1.6 on 2025-03-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='gesto',
            field=models.URLField(blank=True, default=''),
        ),
    ]
