# Generated by Django 5.1.6 on 2025-04-20 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0002_alter_palabra_gesto'),
        ('registro', '0006_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='palabra',
            name='nueva',
        ),
        migrations.AddField(
            model_name='leccion',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='ejercicio.etapa'),
        ),
        migrations.AddField(
            model_name='palabra',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palabras', to='ejercicio.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='ejercicio.etapa'),
        ),
        migrations.CreateModel(
            name='EtapaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_usuario', to='ejercicio.etapa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_usuario', to='registro.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LeccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_usuario', to='ejercicio.leccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones_usuario', to='registro.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PalabraUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras_usuario', to='ejercicio.palabra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras_usuario', to='registro.profile')),
            ],
        ),
    ]
