# Generated by Django 5.1.6 on 2025-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0003_remove_etapa_completada_remove_leccion_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabra',
            name='frase',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='instruccion',
            name='tipo',
            field=models.CharField(choices=[('seleccion', 'Selecciona el gesto correcto para {palabra}'), ('seleccion2', 'Selecciona el gesto correcto a la palabra resaltada'), ('emparejar', 'Empareja las palabras con su respectivo texto'), ('completar', 'Selecciona el gesto que completa la frase'), ('escribir', 'Escribe la palabra que corresponde al gesto'), ('gesto', 'Realiza el siguiente gesto para la palabra {palabra}')], max_length=20),
        ),
    ]
