# Generated by Django 4.2.20 on 2025-06-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0004_palabra_frase_alter_instruccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabrausuario',
            name='precision',
            field=models.FloatField(default=0.0),
        ),
    ]
