# Generated by Django 5.1.6 on 2025-03-30 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_medalla_options'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.medalla'),
        ),
    ]
