# Generated by Django 5.1.6 on 2025-03-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_profile_medalla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='usuario/default.jpg', upload_to='usuario/'),
        ),
    ]
