# Generated by Django 5.1.6 on 2025-04-05 19:35

import registro.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, default='usuario/default.jpg', null=True, storage=registro.storages.ImageStorage(), upload_to='posts/'),
        ),
    ]
