# Generated by Django 5.1.6 on 2025-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_profile_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
