# Generated by Django 5.1.6 on 2025-04-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0003_remove_etapa_completada_remove_leccion_categoria_and_more'),
        ('registro', '0006_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leccion',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejercicio.leccion'),
        ),
    ]
