# Generated by Django 5.1.6 on 2025-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_profile_leccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leccion',
            field=models.IntegerField(default=1),
        ),
    ]
