# Generated by Django 4.2.20 on 2025-06-03 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_profile_leccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
